使用np.linspace時最少要輸入兩個必要數值 'start'  和 'stop' 像是

np.linspace(start, stop)

它會回傳一組 'numpy ndarray' 預設為50個數字，並將輸入的兩個數值等分成49個間隔，且每個數字預設為小數點後8位。

'start' 和 'stop' 大小順序並不限制，np.linspace(0,-1) 也是可以的。

In [1]:
import numpy as np

array = np.linspace(0,1)

print (array)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


再來可以插入第三個數字 'num' , 用來控制陣列內數字的數量，像是

np.linspace(-1, 1, 35) 表示包含-1 及 1 在內，該ndarray共有35個數字，且平分成34個間隔。

另外 'num' 必須為整數(integer, int)且不能為負數。


有時候直觀上我們會將兩數除以 'num' 來得到我們想要的間隔, 

好比說(0, 10, 10) 預期分成10等份 0, 1, 2 ..... 10,

但這其實得要用 (0, 10, 11)才能得到這個預期結果。(0到10分成10等份有11個數字, 所以'num'在這裡得設成11)。

這裡我們可以插入一個boolean值來控制 endpoint (預設為True)。

In [2]:
np.linspace(0, 10, 10, endpoint = False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

我們可以進一步得到間隔值的大小，使用retstep (return step的縮寫) 並設為True

In [3]:
np.linspace(0, 10, 5, retstep = True)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

該指令回傳一個 'tuple', 裡面包含原本的 'ndarray' 和它的間隔值。

你還可以指定 ndarray 內的 default type，要不要為浮點數或整數 ，

In [9]:
np.linspace(0, 10, 5)
np.linspace(0, 10, 5, dtype = int)

array([ 0,  2,  5,  7, 10])

In [ ]:
>>>
[ 0.   2.5  5.   7.5 10. ]
[ 0  2  5  7 10]

當我將 dtype 設為 int 之後, ndarray自動將陣列內的浮點數捨去小數點後數字, 轉變為整數型態。

In [13]:
nz = 61
np.linspace(0, nz, nz, endpoint = False, dtype = int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [25]:
np.linspace(0, nz-1, nz-1, endpoint = False, dtype = int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [28]:
nz = 61
np.linspace(nz, 1, nz)#, dtype = int)#, dtype = int)

array([61., 60., 59., 58., 57., 56., 55., 54., 53., 52., 51., 50., 49.,
       48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37., 36.,
       35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24., 23.,
       22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11., 10.,
        9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])